#!/usr/bin/env bash

BASE=~/.dotfiles
BASE_ETC=$BASE/etc
TARGET=~

EXCLUDE=".config"

###############################################################################
# {{{ Create initial dir structure in HOME
#

mkdir -p ~/Archiv
mkdir -p ~/Dokumente
mkdir -p ~/Downloads
#mkdir -p ~/Musik
mkdir -p ~/Fotos
mkdir -p ~/Shared
mkdir -p ~/Daten

# }}}

###############################################################################
# {{{ Link all files from etc
#

for file in $(find $BASE_ETC -mindepth 1 -maxdepth 1  -name "*" -and -not -name "." )
do
  skip=0
  for excluded in $EXCLUDE
  do
    if [ "$excluded" = "`basename $file`" ]; then
      skip=1
    fi
  done

  if [ $skip -ne 0 ]; then
    #echo "Skipping $file"
    continue
  fi

  #echo "Linking: $file"
  ln -sf $file $TARGET
done

# }}}

###############################################################################
# {{{ Handle excluded subdirs
#

#echo "Processing exceptions"
mkdir -p $TARGET/.config/
for file in $(find $BASE_ETC/.config -mindepth 1 -maxdepth 1  -name "*" -and -not -name "." )
do
  #echo "Linking: $file"
  ln -sf $file $TARGET/.config/
done

# }}}

###############################################################################
# {{{ Link scripts to .local/bin
#

#echo "Linking: $BASE/bin"
mkdir -p $TARGET/.local/bin
for file in $(find $BASE/bin -mindepth 1 -maxdepth 1  -name "*" -and -not -name "." )
do
    #echo $file
    ln -sf $file $TARGET/.local/bin
done

# }}}

###############################################################################
# {{{ Verbose check for broken links
#

find $TARGET -type l -xtype l -print0 | while IFS= read -r -d '' file; do
    if
        # Nix
        [[ "$file" == $HOME/.nix-defexpr/channels ]] ||
        [[ "$file" == $HOME/.nix-profile ]] ||

        [[ "$file" == $HOME/.local/share/Trash/* ]] ||

        # Steam
        [[ "$file" == $HOME/.local/share/Steam/* ]] ||
        [[ "$file" == $HOME/.steam/* ]] ||
        [[ "$file" == $HOME/Spiele/* ]] ||
        [[ "$file" == $HOME/.steampath ]] ||

        # Sockets and Locks
        [[ "$file" == $HOME/.kde/tmp-zen ]] ||
        [[ "$file" == $HOME/.kde/socket-zen ]] ||
        [[ "$file" == $HOME/.config/*/SingletonCookie ]] ||
        [[ "$file" == $HOME/.config/*/SingletonLock ]] ||
        [[ "$file" == $HOME/.config/*/SingletonSocket ]] ||

        [[ "$file" == $HOME/.mozilla/firefox/*/lock ]] ||
        [[ "$file" == $HOME/.thunderbird/*/lock ]] ||
        [[ "$file" == $HOME/.config/pulse/*-runtime ]] ||
        [[ "$file" == $HOME/.cache/* ]] ||
        [[ "$file" == $HOME/.var/app/* ]] ||

        # Projects, Data and Archives
        [[ "$file" == $HOME/Projekte/* ]] ||
        [[ "$file" == $HOME/Daten/* ]] ||
        [[ "$file" == $HOME/Archiv/* ]]
    then
        continue
    fi
    echo "WARN - broken link: $file"
done

# }}}
