#!/bin/sh

# echo 'awesome.restart()' | awesome-client
# sleep 3

dunstify -a "autorandr-predetect" -t 5000 -i display -r "154334" "Display Profile" "$AUTORANDR_MONITORS ($AUTORANDR_CURRENT_PROFILE)"

# Make the internal display less green-ish
xrandr --output eDP-1 --gamma 0.99:0.98:1.0 --brightness 1.0 &

# Restart Awesine as ut does not pickup the change
echo 'awesome.restart()' | awesome-client
